name: sih2025
description: "Comprehensive Waste Management Platform for India"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  
  # State Management
  provider: ^6.1.2
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  
  # Location & Maps
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  
  # Camera & Image
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  
  # Utilities
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.1
  intl: ^0.19.0
  uuid: ^4.5.1
  
  # Translation
  google_mlkit_translation: ^0.13.0
  
  # Animations & Games
  flame: ^1.19.0
  audioplayers: ^6.1.0
  confetti: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.11
  
  # QR Code
  qr_flutter: ^4.1.0
  # qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/games/
    - assets/icons/
  
  # fonts:
  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/fonts/custom_icons.ttf